services:
  db:
    image: mariadb:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: metrics
    healthcheck:
      test: ["CMD", "mysqladmin", "-pexample", "ping"]
      timeout: 5s
      interval: 5s
      retries: 12

  backend:
    build: .
    container_name: server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/metrics"
      - "SPRING_DATASOURCE_USERNAME=root"
      - "SPRING_DATASOURCE_PASSWORD=example"
